name       : kimap
version    : 17.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kimap-17.12.2.tar.xz : 237ce8c8dc794fdfa0d4c18c59f436d9be1ae3579b8a00d49c44e13a99b4cb96
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server.
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
