name       : kimap
version    : 22.12.1
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/kimap-22.12.1.tar.xz : bdd908dd96638f244b2c27afc461df51b04faba790eda946c8017f44058acf0d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(libsasl2)
    - kmime-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
