name       : kimap
version    : 18.08.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kimap-18.08.0.tar.xz : b8769fe7531265bdfdfa4ae3fd5aa8d035582b53e4597ea98c2b569e6fa59a8a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
