name       : kimap
version    : 20.12.1
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kimap-20.12.1.tar.xz : 9bd0b19ec6f8bacb6cf6d2e47949eaa470dde4a7359fd8da1d3cebb1ea55d4f4
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(libsasl2)
    - kmime-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
