name       : kimap
version    : 18.12.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kimap-18.12.3.tar.xz : 00aed701a3bdcc218902998e63e7c587549f77a1aa0d1bd7dad4a1837adc9992
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
