name       : kimap
version    : 17.08.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kimap-17.08.1.tar.xz : 55ebd3abc30c1c8cfa5e03baf559eeee0d67aeec129fcf2a08e0c951823f90ed
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1
    server.
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
