name       : kimap
version    : 19.04.2
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/kimap-19.04.2.tar.xz : 352129ca7aa2de360256392df3fed14b1338fbea1b3d1dda189dffc6629e86e9
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
