name       : kimap
version    : 23.04.2
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kimap-23.04.2.tar.xz : bcc4a1ced8f55e5d7106b3cfb18ee639e23761a3cb23fdb8d63d925907b784de
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a job-based API for interacting with an IMAP4rev1 server
description: |
    This library provides a job-based API for interacting with an IMAP4rev1 server. It manages connections, encryption and parameter quoting and encoding, but otherwise provides quite a low-level interface to the protocol.  This library does not implement an IMAP client; it merely makes it easier to do so.
builddeps  :
    - pkgconfig(libsasl2)
    - kmime-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
